### ISSUE TITLE
readme doesn't explain why you do this

### ISSUE THREAD

**Issue by seamusabshere** [zhulik/pinball#2]
it's not clear what the use cases are

naive interpretation: "why not just use modules?"

**Comment by zhulik** [comment]
https://en.m.wikipedia.org/wiki/Dependency_injection

For me it simplify testing routins, speeds it up and allow to reduce complexity in really big, enterprise-level apps

**Comment by seamusabshere** [comment]
@zhulik can you give an example in the readme? a lot of rubyists (including me) have never needed dependency injection... or at least, if we used it, we didn't know that's what it was

**Comment by shadowbq** [comment]
http://solnic.eu/2013/12/17/the-world-needs-another-post-about-dependency-injection-in-ruby.html

**Comment by phoet** [comment]
there is an excellent book called [design patterns in ruby](http://www.amazon.com/Design-Patterns-Ruby-Russ-Olsen/dp/0321490452) which explains the most popular patterns in software design as described by the Gang of Four, how to implement them in ruby and (most importantly) the "usage in the wild" aka "why you don't need it in ruby because there is a more elegant way".
